import * as React from 'react';
import Head from 'next/head';
import { Inter } from '@next/font/google';
import axios from 'axios';
import { DataGrid } from '@mui/x-data-grid';
import { useQueries, useQuery } from '@tanstack/react-query';
import { RemitaDataItem, TableData } from '@/types';
import _ from 'lodash';

const inter = Inter({ subsets: ['latin'] });

const column = [
  { field: 'id', headerName: 'Known ID', width: 90 },
  { field: 'mandate', headerName: 'Mandate' },
  { field: 'authcode', headerName: 'Authentication Code', width: 150 },
  { field: 'phone', headerName: 'Phone', width: 130 },
  { field: 'tenure', headerName: 'Tenure' },
  { field: 'amount', headerName: 'Amount' },
  { field: 'interest', headerName: 'Interest' },
  { field: 'outstanding', headerName: 'Outstanding' },
  { field: 'repayment', headerName: 'Repayment' },
  { field: 'ramount', headerName: 'RRR Amount' },
  { field: 'Rrepayment', headerName: 'RRR Repayment' },
  { field: 'status', headerName: 'Status', width: 85 },
  { field: 'rtenure', headerName: 'RRR Tenure' },
  { field: 'routstanding', headerName: 'RRR Outstanding' },
  { field: 'verdict', headerName: 'Verdict', width: 80 },
];

export default function Home() {
  const [isRemitaButtonDisabled, setIsRemitaButtonDisabled] =
    React.useState(false);

  const [mergedData, setMergedData] = React.useState<any[] | undefined>();

  const {
    isLoading,
    error,
    data: initialLoansData,
  } = useQuery<TableData[]>({
    queryKey: ['Repodata'],
    queryFn: async () => {
      const { data } = await axios.get('http://localhost:3001/data');
      return data;
    },
  });

  const getRemitaData = async (id: number | string) => {
    const { data } = await axios.get(`http://localhost:3002/${id}`);
    return data;
  };

  const obtainRemitaDataResults = async () => {
    const remitaApiResults = await Promise.all(
      initialLoansData?.map((item) => getRemitaData(item.id)) || []
    );

    const merged = initialLoansData?.map((item1) => {
      return {
        ...item1,
        ...remitaApiResults?.find((item2) => item2?.id === item1?.id),
      };
    });

    setMergedData(merged);
  };

  if (isLoading) {
    return <p>Loading</p>;
  }

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen w-full flex flex-col justify-center items-center mt-16">
        <p className="text-6xl text-blue- my-12">Reconciliation Dashboard</p>

        <div className="w-[90%] flex flex-row justify-between items-center my-8">
          <div className="flex gap-4 items-center">
            <p className="text-center text-2xl">Total Amount</p>

            <button
              className="border-2 py-2 px-5 bg-blue-500 text-white text-lg 
            rounded-md shadow-sm hover:bg-blue-300 hover:shadow-lg"
            >
              {/* {sum} */}
            </button>

            <p className="text-center text-2xl">Total Repayment</p>
            <button
              className="border-2 py-2 px-5 bg-blue-500 text-white text-lg 
            rounded-md shadow-sm hover:bg-blue-300 hover:shadow-lg"
            >
              {/* {pay} */}
            </button>
          </div>

          <button
            className="border-2 py-2 px-5 disabled:cursor-not-allowed disabled:opacity-50 bg-orange-400 text-white text-lg 
            rounded-md shadow-sm hover:bg-orange-300 hover:shadow-lg"
            disabled={isRemitaButtonDisabled}
            onClick={() => {
              obtainRemitaDataResults();
              setIsRemitaButtonDisabled(true);
            }}
          >
            Load
          </button>
        </div>

        <div className="h-screen w-[90%] flex-shrink">
          <DataGrid
            rows={mergedData || initialLoansData || []}
            columns={column}
            initialState={{
              pagination: {
                pageSize: 10,
              },
            }}
          />
        </div>
      </main>
    </>
  );
}
